name: mcconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  dio: ^5.2.2
  http: ^0.13.5
  file_picker: ^8.1.2
  http_parser: ^4.0.2
  mime: ^1.0.0
  qr_flutter: ^4.1.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.7.0
  screenshot: ^3.0.0
  csv: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
